# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  'node-10':
    docker:
      - image: circleci/node:10
    working_directory: ~/typescript-starter
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: npx nyc report --reporter=lcov | npx codecov
      - run: npm run cov:check
  'node-latest':
    docker:
      - image: circleci/node:latest
    working_directory: ~/typescript-starter
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: npx nyc report --reporter=lcov | npx codecov
      - run: npm run cov:check
  'docs-deploy':
    docker:
        - image: circleci/node:10
    working_directory: ~/typescript-starter
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm run doc:html
      - run: git config user.email "ci-build@klukas.net"
      - run: git config user.name "ci-build"
      - run: npm run doc:publish

workflows:
  version: 2
  build:
    jobs:
      - node-10
      - node-latest
      - docs-deploy:
          requires:
            - node-10
            - node-latest
