version: 2.1
jobs:
  'node-8':
    docker:
      - image: circleci/node:8
    working_directory: ~/typescript-starter
    steps:
      - test
  'node-10':
    docker:
      - image: circleci/node:10
    working_directory: ~/typescript-starter
    steps:
      - test
  'node-12':
    docker:
      - image: circleci/node:12
    working_directory: ~/typescript-starter
    steps:
      - test

commands:
  test:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: npm run cov:send

workflows:
  version: 2
  build:
    jobs:
      - node-8
      - node-10
      - node-latest
