name: Automerge Dependabot PRs

on:
  pull_request:
    types:
      - opened

jobs:
  dependabot-automerge:
    uses: relaycorp/shared-workflows/prs.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
